-- MT Importados — Setup do banco de dados Supabase
-- Rode este script inteiro no SQL Editor do seu projeto (Supabase Dashboard > SQL Editor > New query)

-- 1. Tabela de marcas
create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text unique not null
);

-- 2. Tabela de produtos (schema alinhado com o front-end)
create table if not exists public.products (
  id text primary key,
  sku text,
  title text not null,
  brand text,
  "categorySlug" text not null,
  "categoryName" text,
  department text,
  price numeric not null,
  "pixDiscount" numeric default 8,
  installments integer default 8,
  rating numeric default 5,
  "reviewsCount" integer default 1,
  image text,
  gallery jsonb default '[]'::jsonb,
  badge text,
  "top5Rank" integer,
  variants jsonb default '["Padrão"]'::jsonb,
  "inStock" boolean default true,
  "stockQuantity" integer default 0,
  description text,
  specs jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 3. Segurança (RLS): leitura pública, escrita só para usuários autenticados (o admin logado)
alter table public.products enable row level security;
alter table public.brands enable row level security;

create policy "Public read products" on public.products for select using (true);
create policy "Authenticated manage products" on public.products for all to authenticated using (true) with check (true);

create policy "Public read brands" on public.brands for select using (true);
create policy "Authenticated manage brands" on public.brands for all to authenticated using (true) with check (true);

-- 4. Bucket de imagens dos produtos (público para leitura, upload só autenticado)
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "Authenticated upload product images" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images');

create policy "Authenticated update product images" on storage.objects
  for update to authenticated using (bucket_id = 'product-images');

create policy "Authenticated delete product images" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images');

-- 5. Marcas iniciais (opcional, pode editar depois pelo painel)
insert into public.brands (name) values
  ('Maison Alhambra'), ('Lattafa'), ('Armaf'), ('MT Importados')
on conflict (name) do nothing;
